version: '3.8'
services:
  app:
    container_name: thumbnail-api
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - WEBHOOK_URL=${WEBHOOK_URL}
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: